# apache httdp + tomcat
web:
  build: web
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - ./webapps:/tomcat/webapps
    - ./www:/var/www
    - ./data/aduna:/root/.aduna/openrdf-sesame
  restart: always

virtuoso:
  image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1 
  environment:
    SPARQL_UPDATE: "true"
    DEFAULT_GRAPH: "https://dataone.org"
    VIRT_Server_DirsAllowed: "/data/dumps"
  volumes:
    - ./data/virtuoso:/data
  ports:
    - "8890:8890"

worker:
  build: worker
  links:
    - web
    - redis
    - virtuoso
  volumes:
    - ./d1lod:/d1lod
    - ./www:/www
  environment:
    - PYTHONPATH=/d1lod:/usr/lib/python2.7/dist-packages
  restart: always

scheduler:
  build: scheduler
  links:
    - web
    - redis
    - virtuoso
  volumes:
    - ./d1lod:/d1lod
  environment:
    - PYTHONPATH=/d1lod:/usr/lib/python2.7/dist-packages
  restart: always

redis:
  build: redis
  volumes:
    - ./data/redis:/data
  restart: always

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
  environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    - xpack.monitoring.enabled=false
    - xpack.watcher.enabled=false
    - ES_JAVA_OPTS=-Xms1g -Xmx1g
  ports:
    - "9200:9200"
    - "9300:9300"
  ulimits:
    nofile:
      soft: 65536
      hard: 65536
    memlock:
      soft: -1
      hard: -1

kibana:
  image: docker.elastic.co/kibana/kibana:6.1.1
  ports:
    - "5601:5601"
  links:
    - elasticsearch:elasticsearch

logstash:
  image: logstash:latest
  links:
    - elasticsearch
  environment:
    LOGSPOUT: 'ignore'
  volumes:
    - ./logstash/config:/config-dir
  command: -f /config-dir/logstash.conf

logspout:
  image: gliderlabs/logspout:latest
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  command: syslog://logstash:5000
  links:
    - logstash

cadvisor:
  image: google/cadvisor:latest
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  ports:
    - "8888:8080"

rqdashboard:
  build: rqdashboard
  links:
    - redis
  ports:
    - "9181:9181"
