version: "3.10"
services:
  virtuoso:
    build: deploy/docker/virtuoso
    environment:
      DBA_PASSWORD: "dba"
    ports:
      - "8890:8890"
  redis:
    image: redis
  rqdashboard:
    image: eoranged/rq-dashboard
    environment:
      RQ_DASHBOARD_REDIS_URL: "redis://redis:6379"
    ports:
      - "9181:9181"
  web:
    build: deploy/docker/web
    ports:
      - "8080:8080"
    environment:
      VIRTUOSO_URL: "http://virtuoso:8890"
  worker_default:
    build: slinky
    environment:
      VIRTUOSO_URL: "http://virtuoso:8890"
      REDIS_URL: "redis://redis:6379"
    command: "slinky work default"
  worker_dataset:
    build: slinky
    environment:
      VIRTUOSO_URL: "http://virtuoso:8890"
      REDIS_URL: "redis://redis:6379"
    command: "slinky work dataset"
  schedule:
    build: slinky
    environment:
      REDIS_URL: "redis://redis:6379"
    command: "slinky schedule"
  scheduler:
    build: slinky
    environment:
      REDIS_URL: "redis://redis:6379"
    command: "rqscheduler --host redis -i 10"
