nginx:
  image: nginx:1.9.7
  ports:
    - "80:80"
  volumes:
    - ./www:/usr/share/nginx/html

worker:
  build: worker
  links:
      - graphdb
      - redis
  volumes:
    - ./d1lod:/d1lod
    - ./www:/www
  environment:
    - PYTHONPATH=$PYTHONPATH:/glharvest:/d1lod/:/usr/lib/python2.7/dist-packages
    
scheduler:
  build: scheduler
  links:
    - graphdb
    - redis
  volumes:
    - ./d1lod:/d1lod
  environment:
    - PYTHONPATH=$PYTHONPATH:/glharvest:/d1lod/:/usr/lib/python2.7/dist-packages

graphdb:
  image: tomcat:8.0-jre8
  ports:
    - "8080:8080"
  volumes:
    - ./webapps:/usr/local/tomcat/webapps/

redis:
  image: redis:3.0.5

# elasticsearch:
#   image: elasticsearch:latest
#   command: elasticsearch -Des.network.host=0.0.0.0
#   ports:
#     - "9200:9200"
#     - "9300:9300"
#
# kibana:
#   image: kibana:latest
#   ports:
#     - "5601:5601"
#   links:
#     - elasticsearch:elasticsearch
#
# logstash:
#   image: logstash:latest
#   links:
#     - elasticsearch
#   environment:
#     LOGSPOUT: 'ignore'
#   volumes:
#     - ./logstash/config:/config-dir
#   command: -f /config-dir/logstash.conf
#
# logspout:
#   build: ./logspout
#   volumes:
#     - /var/run/docker.sock:/tmp/docker.sock
#   command: syslog://logstash:5000
#   links:
#     - logstash
#
# cadvisor:
#   image: google/cadvisor:latest
#   volumes:
#     - /:/rootfs:ro
#     - /var/run:/var/run:rw
#     - /sys:/sys:ro
#     - /var/lib/docker/:/var/lib/docker:ro
#   ports:
#     - "8888:8080"
