version: "3"
services:
  web:
    build: web
    ports:
      - "80:80"
    volumes:
      - www-home:/var/www
    restart: always

  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "https://dataone.org"
      VIRT_Server_DirsAllowed: "/data/dumps"
    volumes:
      - virtuoso-home:/data
    ports:
      - "127.0.0.1:8890:8890"

  worker:
    build: worker
    volumes:
      - ./d1lod:/d1lod
    environment:
      - PYTHONPATH=/d1lod:/usr/lib/python2.7/dist-packages
    restart: always

  scheduler:
    build: scheduler
    volumes:
      - ./d1lod:/d1lod
    environment:
      - PYTHONPATH=/d1lod:/usr/lib/python2.7/dist-packages
    restart: always

  redis:
    image: 'bitnami/redis:latest'
    volumes:
      - redis-home:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    ports:
      - "127.0.0.1:5601:5601"
    links:
      - elasticsearch:elasticsearch

  logstash:
    image: logstash:6.6.1
    links:
      - elasticsearch
    environment:
      LOGSPOUT: 'ignore'
    volumes:
      - ./logstash/config:/config-dir
    command: -f es-home/logstash.conf

  logspout:
    image: gliderlabs/logspout:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: syslog://logstash:5000
    links:
      - logstash

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "127.0.0.1:8888:8080"

  rqdashboard:
    build: rqdashboard
    links:
      - redis
    ports:
      - "9181:9181"

volumes:
  www-home: {}
  virtuoso-home: {}
  redis-home: {}
