apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels: {{- include "slinky.labels" . | nindent 4 }}
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
        - name: master
          image: "{{ .Values.image.redis.name }}:{{ .Values.image.redis.tag }}"
          command: ["redis-server", "/redis-master/redis.conf"]
          args: ["--protected-mode", "no"]
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          ports:
            - containerPort: {{ .Values.port.redis }}
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /data
              name: redis-volume
            - mountPath: /redis-master
              name: config
      volumes:
        - name: redis-volume
        #   persistentVolumeClaim:
        #     claimName: cephfs-slinky-pvc
        - name: config
          configMap:
            name: redis-config
            items:
              - key: redis-config
                path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
    - port: {{ .Values.port.redis }}
      targetPort: {{ .Values.port.redis }}
  selector:
    app: redis
    role: master
    tier: backend
