apiVersion: batch/v1
kind: Job
metadata:
  name: schedule
spec:
  template:
    spec:
      containers:
      - name: schedule
        image: slinkythegraph/slinky:0.3.0
        command: ["slinky"]
        args: ["schedule"]
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
      restartPolicy: OnFailure
