---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slinky-pvc
  namespace: slinky
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
  storageClassName: csi-rbd-sc

