---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-default
  labels: {{- include "slinky.labels" . | nindent 4 }}
    app: worker-default
spec:
  selector:
    matchLabels:
      app: worker-default
  template:
    metadata:
      labels:
        app: worker-default
    spec:
      containers:
        - name: worker-default
          image: "{{ .Values.image.slinky.name }}:{{ default .Chart.AppVersion .Values.image.slinky.tag }}"
          imagePullPolicy: IfNotPresent
          command: ["slinky"]
          args: ["work", "default"]
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
