apiVersion: v1
kind: Service
metadata:
  name: virtuoso
spec:
  ports:
  - name: virtuoso
    port: 8890
    targetPort: 8890
  selector:
    app: virtuoso
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
