---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: slinky
  name: slinky-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
