---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-slinky-pvc
  namespace: slinky
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  volumeName: cephfs-slinky-pv