---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-default
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-default
  template:
    metadata:
      labels:
        app: worker-default
    spec:
      containers:
        - name: worker-default
          image: thomasthelen/slinky:latest
          imagePullPolicy: Always
          command: ["slinky"]
          args: ["work", "default", "--prod", "--debug"]
          volumeMounts:
            - mountPath: /d1lod
              name: worker-volume
      volumes:
        - name: worker-volume
          persistentVolumeClaim:
            claimName: slinky-pvc
