version: "3.10"
services:
  virtuoso:
    image: thomasthelen/virtuoso
    environment:
      DBA_PASSWORD: "dba"
    ports:
      - "8890:8890"
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    ports:
      - "8080:8080"
  redis:
    image: redis
    ports:
      - "6379:6379"
