version: "3.10"
services:
  virtuoso:
    image: slinkythegraph/virtuoso
    environment:
      DBA_PASSWORD: "dba"
    ports:
      - "8890:8890"
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    ports:
      - "8080:8080"
  redis:
    image: redis
    ports:
      - "6379:6379"
  slinky:
    image: slinkythegraph/slinky
    entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GRAPH_HOST=http://virtuoso
      - GRAPH_PORT=8890
      - BLAZEGRAPH_HOST=http://blazegraph
      - BLAZEGRAPH_PORT=8080

  web:
    image: slinkythegraph/web
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GRAPH_HOST=http://virtuoso
      - GRAPH_PORT=8890
      - BLAZEGRAPH_HOST=http://blazegraph
      - BLAZEGRAPH_PORT=8080
    ports:
      - "80:80"
