version: "3.9"
services:
  virtuoso:
    image: openlink/virtuoso-opensource-7
    environment:
      DBA_PASSWORD: "dba"
    ports:
      - "8890:8890"
  virtuoso_setup:
    build: tests/extras/virtuoso_init
    depends_on:
      - virtuoso
    restart: "no"
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    ports:
      - "8080:8080"
  redis:
    image: redis
    ports:
      - "6379:6379"
