namespace: slinky

image:
  slinky:
    name: slinkythegraph/slinky
  redis:
    name: bitnami/redis
    tag: "7.0.4"

service:
  type: ClusterIP

urls:
  redis: "redis://redis:6379"
  virtuoso: "http://virtuoso:8890"
  rqdashboard: "redis://redis:6379"

port:
  redis: 6379
  virtuoso: 8890
  rqdashboard: 9181
  web: 8080

# Placeholder values for ingress
ingress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  tls:
    secretName: ""
