---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: virtuoso-pv
  labels:
    type: local
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtuoso-pvc
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtuoso
  labels:
    app: virtuoso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtuoso
  template:
    metadata:
      labels:
        app: virtuoso
    spec:
      containers:
      - name: virtuoso
        image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
        env:
        - name: DEFAULT_GRAPH
          value: https://dataone.org
        - name: SPARQL_UPDATE
          value: "true"
        - name: VIRT_Server_DirsAllowed
          value: /data/dumps
        ports:
        - containerPort: 8890
        volumeMounts:
        - mountPath: /data
          name: virtuoso-pvc
      volumes:
        - name: virtuoso-pvc
          persistentVolumeClaim:
            claimName: virtuoso-pvc
