---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - env:
            - name: PYTHONPATH
              value: /d1lod:/usr/lib/python3.9/dist-packages
          image: thomasthelen/worker:latest
          name: worker
          command: ["python3"]
          args: ["-u", "work.py"]
          volumeMounts:
            - mountPath: /d1lod
              name: worker-volume
      volumes:
        - name: worker-volume
          persistentVolumeClaim:
            claimName: slinky-pvc
