name: docs

on: push

jobs:
  document:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dataoneorg/slinky:latest
    steps:
    - name: Install rsync 📚
      run: |
        apt-get update && apt-get install -y rsync
    - uses: actions/checkout@v3
    - name: pip install
      working-directory: ./slinky
      run: python -m pip install .[docs]
    - name: Build documentation
      run: sphinx-build . _build
      working-directory: ./slinky/docs
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./slinky/docs/_build
