name: pytest

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dataoneorg/slinky:latest
    steps:
    - uses: actions/checkout@v3
    - name: pip install
      working-directory: ./slinky
      run: python -m pip install .[test]
    - name: pytest
      working-directory: ./slinky
      run: python -m pytest
